openapi: 3.1.0
servers:
    - url: http://localhost:8080
      description: Local server
info:
    title: CarDB API
    version: 1.0.0
    description: API for searching car models, variations, engine options, and specs
    license:
        name: MIT
        url: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

paths:
    /cars:
        get:
            summary: Get cars
            description: Retrieves a list of car models
            operationId: getCars
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListCarsResponse'
                '400':
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                '401':
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /car/{slug}:
        get:
            summary: Get car
            description: Retrieves a single car model
            operationId: getCar
            parameters:
                - name: slug
                  in: path
                  description: Slug of car model to retrieve
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CarModel'
                '400':
                    description: Invalid ID supplied
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                '401':
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                '404':
                    description: Car model not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /brands:
        get:
            summary: Get car brands
            description: Retrieves a list of car brands
            operationId: getBrands
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListBrandsResponse'
                '400':
                    description: Invalid query parameter
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                '401':
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /brands/{slug}:
        get:
            summary: Get car brand
            description: Retrieves a single car brand
            operationId: getBrand
            parameters:
                - name: slug
                  in: path
                  description: Slug of the car brand to retrieve
                  required: true
                  schema:
                      type: string
            responses:
                '200':
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CarBrand'
                '400':
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                '401':
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                '404':
                    description: Car brand not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        ListCarsResponse:
            type: object
            properties:
                cars:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: number
                            name:
                                type: string
                            slug:
                                type: string
                            body_type:
                                $ref: '#/components/schemas/BodyType'

        ListBrandsResponse:
            type: object
            properties:
                brands:
                    type: array
                    items:
                        $ref: '#/components/schemas/CarBrand'
        CarModel:
            type: object
            properties:
                id:
                    type: number
                name:
                    type: string
                slug:
                    type: string
                body_type:
                    $ref: '#/components/schemas/BodyType'
                brand:
                    $ref: '#/components/schemas/CarBrand'
                generations:
                    type: array
                    items:
                        $ref: '#/components/schemas/CarGeneration'

        CarGeneration:
            type: object
            properties:
                id:
                    type: integer
                name:
                    type: string
                production_start_year:
                    type: integer
                production_end_year:
                    type: 
                        - integer
                        - null
                tire_size:
                    type: string
                length_mm:
                    type: integer
                width_mm:
                    type: integer
                height_mm:
                    type: integer
                ground_clearance_mm:
                    type: integer
                cargo_volume_litres:
                    type: integer
                engineOptions:
                    type: array
                    items:
                        $ref: '#/components/schemas/EngineOption'
                # Add weight

        EngineOption:
            type: object
            properties:
                id:
                    type: integer
                name:
                    type: string
                fuel_type:
                    $ref: '#/components/schemas/FuelType'
                drive_type:
                    $ref: '#/components/schemas/DriveType'
                transmission_type:
                    $ref: '#/components/schemas/TransmissionType'
                number_of_gears:
                    type: integer
                number_of_cylinders:
                    type: integer
                cylinder_layout:
                    $ref: '#/components/schemas/CylinderLayout'
                fuel_econonmy_city_l_per_100km:
                    type: number
                fuel_economy_highway_l_per_100km:
                    type: number
                fuel_economy_combined_l_per_100km:
                    type: number
                power_kw:
                    type: number
                power_hp:
                    type: number
                power_bhp:
                    type: number
                top_speed_kph:
                    type: integer
                acceleration_0_100_kph:
                    type: number

        CarBrand:
            type: object
            properties:
                id:
                    type: integer
                name:
                    type: string
                origin_country:
                    type: string
                website:
                    type: string
                slug:
                    type: string

        BodyType:
            type: string
            enum:
                - SEDAN
                - COUPE
                - CONVERTIBLE
                - WAGON
                - HATCHBACK
                - SUV
                - TRUCK
                - VAN

        FuelType:
            type: string
            enum:
                - PETROL
                - DIESEL
                - ELECTRIC
                - HYBRID
                - PLUG_IN_HYBRID
                - HYDROGEN
        
        DriveType:
            type: string
            enum:
                - FWD
                - RWD
                - AWD
        
        TransmissionType:
            type: string
            enum:
                - MANUAL
                - AUTOMATIC
                - CVT
                - DCT
        
        CylinderLayout:
            type: string
            enum:
                - INLINE
                - V
                - FLAT
                - ROTARY
                - ELECTRIC
                - HYDROGEN

        Error:
            type: object
            properties:
                statusCode:
                    type: integer
                message:
                    type: string
