spring:
  application:
    name: car-search
  datasource:
    url: jdbc:postgresql://localhost:5432/carsearch
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
